
sudo: required

matrix:
  include:
    - env: OS='ubuntu:18.04'
    - env: OS='centos:7'

before_install:
  - docker pull $OS

# install:
#   - docker run -d $OS /bin/sh -c "provision container if you do not have a prebuilt image and are instead using base images"

script:
  - if [ "$OS" = "centos:7" ]; then  docker run -d $OS /bin/sh -c "curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered > nr.sh && echo y | bash nr.sh"; fi
