
dist: trusty

sudo: required

env:
    matrix:
      # - OS=ubuntu DIST=xenial
      # - OS=ubuntu DIST=bionic
      # - OS=ubuntu DIST=disco
      # - OS=ubuntu DIST=eoan
      - OS=debian DIST=jessie
      - OS=debian DIST=stretch
      - OS=debian DIST=buster


before_script:
  - sudo echo $NVM_DIR
  - sudo echo $(/etc/os_release)
  - sudo apt -y install libstdc++6 
  - sudo rm -rf $NVM_DIR ~/.npm ~/.bower
  - sudo echo $(node -v)
  - sudo echo $TRAVIS_DIST $DIST
  - if [ "$DIST" = "jessie" ]; then echo "VERSION_ID=\"8\"" > /etc/os-release ; fi

script:
  - curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered > nr.sh
  - echo y | bash nr.sh